name: Build and deploy Node.js app to Azure Web App - eliza-test

on:
  push:
    branches:
      - dependabot/npm_and_yarn/pnpm-9.15.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0

      - name: Install, build, and test with pnpm
        run: |
          pnpm install
          pnpm run build --if-present
          pnpm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0634CBDB3ACD4C6CAE391B23D7CD4781 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C033FFD2C4DE4E628CFA9DAA4D1683C4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD65F8CB58C6440EAB988DB26C70B5F5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eliza-test'
          slot-name: 'Production'
          package: .
